# Generated by Django 5.2.8 on 2025-11-27 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис завдання')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайній термін')),
                ('status', models.CharField(choices=[('Новий', 'Новий'), ('В процесі', 'В процесі'), ('Завершено', 'Завершено')], default='Новий', max_length=50, verbose_name='Статус завдання')),
                ('priority', models.CharField(choices=[('Низький', 'Низький'), ('Середній', 'Середній'), ('Високий', 'Високий')], default='Низький', max_length=50, verbose_name='Пріоритет завдання')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
