# Generated by Django 5.2.8 on 2025-11-30 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tast_tracer_app', '0002_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='createde_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='createde_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
