# Generated by Django 5.2.8 on 2025-12-14 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tast_tracer_app', '0003_coment_createde_at_task_createde_at_task_update_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='createde_at',
            new_name='created_at',
        ),
    ]
